apiVersion: apps/v1
kind: Deployment
metadata:
  name: packs-proxy-dp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: packs-proxy-dp
  template:
    metadata:
      labels:
        app: packs-proxy-dp
    spec:
      containers:
        - name: packs-proxy-dp
          image: giuseppebonanno99/packsproxy:latest
          ports:
            - containerPort: 3001

---
apiVersion: v1
kind: Service
metadata:
  name: packs-proxy-dp
spec:
  selector:
    app: packs-proxy-dp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
