apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /shared/uploads/
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-manager-dp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-manager-dp
  template:
    metadata:
      labels:
        app: helm-manager-dp
    spec:
      containers:
        - name: helm-manager-dp
          image: giuseppebonanno99/helmmanager:latest
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: /shared/uploads/
              name: shared-storage
            - name: kubeconfig-volume
              mountPath: /helm-storage/.kube/config
              subPath: config
          env:
            - name: KUBECONFIG
              value: "/helm-storage/.kube/config"
      volumes:
        - name: kubeconfig-volume
          configMap:
            name: kubeconfig
            items:
              - key: config
                path: config
        - name: shared-storage
          persistentVolumeClaim:
            claimName: shared-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: helm-manager
spec:
  selector:
    app: helm-manager-dp
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---

