apiVersion: v1
kind: PersistentVolume
metadata:
  name: kluster-ui-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/shared/pv-kluster-ui/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kluster-ui-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kluster-ui-dp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kluster-ui-dp
  template:
    metadata:
      labels:
        app: kluster-ui-dp
    spec:
      containers:
        - name: kluster-ui-dp
          image: node:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /data
              name: kluster-ui-storage
          command:
            [
              /bin/sh,
              -c,
              "cd /data && npm install && npm run build && npm run dev",
            ]
      volumes:
        - name: kluster-ui-storage
          persistentVolumeClaim:
            claimName: kluster-ui-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: kluster-ui-dp
spec:
  selector:
    app: kluster-ui-dp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
