name: Build Helm Package
on:
  push:
    paths:
      - "Kluster/**"

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node helm tools
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: get current date
        id: date
        run: echo "VERSION=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: modify Chart.yaml version and appVersion
        run: |
          sed -i "s/version: .*/version: ${{ env.VERSION }}/g" ${{ github.workspace }}/Kluster/Chart.yaml
          sed -i "s/appVersion: .*/appVersion: \"${{ env.VERSION }}\"/g" ${{ github.workspace }}/Kluster/Chart.yaml

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Package Helm Chart
        run: |
          mkdir -p /charts
          helm package /Kluster -d /charts

      - name: Update Helm Repository Index
        run: |
          helm repo index /charts/ --url https://github.com/GiuseppeBnn/Kluster/charts

      - name: Commit and Push updated index.yaml
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "GiuseppeBnn"
          git add /charts/*
          git commit -m "ci: update Helm repo index for version ${{ env.new_version }}"
          git push
