name: Build PACKSProxy Component Image
on:
  push:
    paths:
      - "components/proxy/**"
      - ".github/workflows/build-proxy_image.yml"
  workflow_dispatch:

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get current date
        id: date
        run: echo "VERSION=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push the PacksProxy Component Image
        uses: docker/build-push-action@v5
        with:
          context: components/proxy
          file: components/proxy/Dockerfile
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/packsproxy:${{ env.VERSION }}
            ${{ secrets.DOCKER_USERNAME }}/packsproxy:latest
          platforms: linux/amd64
          builder: default
          push: true
