name: Build Helm Manager Component Image
on:
  push:
    paths:
      - "components/helm-manager/**"
      - ".github/workflows/build_helm-manager_image.yml"
  workflow_dispatch:
jobs:
  go_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - name: Build the Helm Manager Component Image
        run: |
          cd components/helm-manager
          go build -o helm-manager
  docker_build:
    runs-on: ubuntu-latest
    needs: go_build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Version from Git tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push the Helm Manager Component Image
        uses: docker/build-push-action@v5
        with:
          context: components/helm-manager
          file: components/helm-manager/Dockerfile
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/helm-manager:${{ env.VERSION }}
            ${{ secrets.DOCKER_USERNAME }}/helm-manager:latest
            ${{ secrets.DOCKER_USERNAME }}/helm-manager:${{ env.VERSION }}-${{ github.sha }}
          platforms: linux/amd64
          builder: default
          labels: |
            org.opencontainers.image.title=Helm Manager
            org.opencontainers.image.description=Helm Manager Component
            org.opencontainers.image.version=${{ env.VERSION }}
          push: true
